### ISSUE TITLE
请问现在使用的时候报错,怎么解决

### ISSUE THREAD

**Issue by chenyunxuan** [qddegtya/v-circle#4]
ERROR in ./~/_css-loader@0.26.4@css-loader!./~/_vue-loader@10.3.0@vue-loader/lib/style
-rewriter.js?id=data-v-382ba514&scoped=true!./~/_sass-loader@4.1.1@sass-loader?indentedSyntax!./~/_vue-loader@10.3.0@vue-loader/lib/selector.js?type=styles&index=0!./~/_v-circle@0.1.3@v-circle/components/css-circle.vue
Module build failed:
  .v-circle {
          ^
      Invalid CSS after ".v-circle {": expected "}", was "{"
      in /zxy/zxy9/student-app/node_modules/_v-circle@0.1.3@v-circle/components/css-circle.vue (line 19, column 12)

**Comment by mediafigaro** [comment]
<style lang="sass" scoped> 
=>
<style lang="scss" scoped>

**Comment by mediafigaro** [comment]
@chenyunxuan see https://github.com/qddegtya/v-circle/pull/6

**Comment by qddegtya** [comment]
close

**Comment by GarryDeng** [comment]
.0.1.3@v-circle这个框架似乎有问题，里面.0.1.3@v-circle\components\css-circle.vue里面的lang="scss"写成lang="sass"了
