### ISSUE TITLE
interactive mode on/off

### ISSUE THREAD

**Issue by mediafigaro** [qddegtya/v-circle#7]
Hello, nice project, thanks. It would be possible to add a prop to switch off the interactive functionality : 

```
props: [
..
'interactive',
..

methods: {
setPv() {
if (!this.interactive) return
...

```

**Comment by qddegtya** [comment]
close #7

**Comment by qddegtya** [comment]
@all-contributors add @qddegtya for code, infra, maintenance

**Comment by qddegtya** [comment]
@all-contributors add @mediafigaro for code
